id: sample
pretrained: null
seed: 2612
amp: false
model:
    name: SelfSupervisedGaze
    args:
        config:
            device: cuda 
            sequence_length: 400  
            image_size: 256
            hidden_size: 512
            num_hidden_layers: 3
            num_attention_heads: 4
            intermediate_size: 784
            hidden_dropout_prob: 0.0
            attention_probs_dropout_prob: 0.0
optimizer:
    name: AdamW
    args:
        lr: 4.0e-3
loss:
    name: CrossEntropyLoss
    args:
        label_smoothing: 0.1
metric:
    - name: Accuracy
      args:
    - name: F1
      args:
        nclasses: 10
scheduler: 
    name: WarmupLinearCosineAnnealing
    args:
        lr_warmup_epochs: 5
dataset: 
    train:
        name: GazeSelfSupDataset
        args:
            metadata: '/home/ptthang/gaze_sample/data_here/reflacx_new_metadata_train.json'
        loader:
            name: DataLoader
            args:
                batch_size: 64
                shuffle: True
                pin_memory: True
    val:
        name: GazeSelfSupDataset
        args:
            metadata: '/home/ptthang/gaze_sample/data_here/reflacx_new_metadata_train.json'
        loader:
            name: DataLoader
            args:
                batch_size: 1
                pin_memory: True

trainer: 
    nepochs: 600
    val_step: 1
    log_step: 1
    log_dir: runs
