id: sample
pretrained: null
seed: 2612
amp: true
model:
    name: SelfSupervisedGaze
    args:
        sequence_length: 400  
        image_size: 224
        hidden_size: 2
        num_attention_heads: 6
        intermediate_size: 784
        hidden_dropout_prob: 0.0
optimizer:
    name: AdamW
    args:
        lr: 4.0e-3
loss:
    name: CrossEntropyLoss
    args:
        label_smoothing: 0.1
metric:
    - name: Accuracy
      args:
    - name: F1
      args:
        nclasses: 10
scheduler: 
    name: WarmupLinearCosineAnnealing
    args:
        lr_warmup_epochs: 5
dataset: 
    train:
        name: CIFAR10Dataset
        args:
            datapath: ['data/cifar-10-batches-py/data_batch_1', 'data/cifar-10-batches-py/data_batch_2', 'data/cifar-10-batches-py/data_batch_3','data/cifar-10-batches-py/data_batch_4','data/cifar-10-batches-py/data_batch_5']
            metapath: 'data/cifar-10-batches-py/batches.meta'
        loader:
            name: DataLoader
            args:
                batch_size: 256
                shuffle: True
                pin_memory: True
    val:
        name: CIFAR10Dataset
        args:
            datapath: ['data/cifar-10-batches-py/test_batch']
            metapath: 'data/cifar-10-batches-py/batches.meta'
        loader:
            name: DataLoader
            args:
                batch_size: 256
                pin_memory: True

trainer: 
    nepochs: 600
    val_step: 1
    log_step: 1
    log_dir: runs
